export { default as Logo } from './logo.svg'
export { default as Login } from './login.svg'
export { default as Cart } from './cart.svg'
export { default as Badge } from './Badge.svg'
export { default as Play } from './Play.svg'
export { default as Line } from './Line.svg'
export { default as Facebook } from './facebook.svg'
export { default as Twitter } from './twitter.svg'
export { default as Linkdin } from './linkdin.svg'
export { default as box_dot } from './box_dot.svg'
export { default as Circle_Dash} from './Circle_Dash.svg'