export { default as Logo } from './logo.svg'
export { default as Login } from './login.svg'
export { default as Cart } from './cart.svg'
export { default as Badge } from './Badge.svg'
export { default as Play } from './Play.svg'
