export { default as Logo } from "./logo.svg";
export { default as Login } from "./login.svg";
export { default as Cart } from "./cart.svg";
export { default as Badge } from "./Badge.svg";
export { default as Play } from "./Play.svg";
export { default as Line } from "./Line.svg";
export { default as Facebook } from "./facebook.svg";
export { default as Twitter } from "./twitter.svg";
export { default as Linkdin } from "./linkdin.svg";
export { default as Box_dot } from "./box_dot.svg";
export { default as Circle_Dash } from "./Circle_Dash.svg";
export { default as Polegone } from "./Poligone.svg";
export { default as Vector } from "./Vector.svg";
export { default as Product } from "./Product.svg";
export { default as Photo } from "./Photogrzphi.svg";
export { default as Return } from "./Return.svg";
export { default as Circle } from "./Circle_dot.svg";
export { default as IconAllIcuive } from "./iconAllIcuive.svg";
export { default as IconAmajone } from "./iconAmajone.svg";
export { default as IconCamera } from "./IconCamera.svg";
export { default as IconCvService } from "./iconCvService.svg";
export { default as IconGraphicDesign } from "./iconGraphicDesign.svg";
export { default as IconInfographics } from "./iconInfographics.svg";
export { default as IconLinkdin } from "./iconLinkdin.svg";
export { default as IconPersone } from "./iconPersone.svg";
export { default as IconPlay } from "./iconPlay.svg";
export { default as IconRestart } from "./IconRestart.svg";
export { default as IconseoCopywriting } from "./iconseoCopywriting.svg";
export { default as PlayButtonIcon } from "./playButton.svg";
export { default as IconTv } from "./iconTv.svg";
export { default as Iconvideoinfographics } from "./iconvideoinfographics.svg";
export { default as IconwebBuild } from "./iconwebBuild.svg";

export { default as LogoPaymentMethod } from "./logo_payment_methode.svg";
export { default as LogoFbLinkComponent } from "./logo_fb_link_group.svg";
export { default as LogoCarbonMap } from "./carbon_map.svg";
export { default as LogoLightEmail } from "./mdi-light_email.svg";
export { default as LogoPhoneRound } from "./ic_round-phone.svg";
export { default as LogoProductPaparazzi } from "./logoProductPaparazzi.svg";


export { default as OurbrandeImg } from "./ourbrandeImg.svg";
export { default as OurBuildsTrust } from "./ourBuildsTrust.svg";
export { default as OurConnect } from "./ourConnect.svg";
export { default as OurEnhances } from "./ourEnhances.svg";
export { default as OurImproves } from "./ourImproves.svg";
export { default as OurmeetCustomers } from "./ourmeetCustomers.svg";
export { default as OurPurchasing } from "./ourPurchasing.svg";
export { default as OurRequire } from "./ourRequire.svg";
export { default as OurSupportsOmnichanner } from "./ourSupportsOmnichanner.svg";
export { default as ZIcon } from "./ZIncons.svg";
export { default as Pattern } from "./Pattern.svg";

export { default as ProducImajon } from "./produc_imajon_small_icon.svg";
export { default as Product_Chart } from "./product_Chart Infographic.svg";
export { default as Product_Cv } from "./product_Cv.svg";
export { default as Product_home } from "./product_home.svg";
export { default as Product_linkedin_small } from "./product_linkedin_small.svg";
export { default as Product_network } from "./product_network.svg";
export { default as Product_no_img } from "./product_no_img.svg";
export { default as Product_pan_graphic } from "./product_pan_graphic.svg";
export { default as Product_Pay } from "./product_Pay per Click.svg";
export { default as Product_personalguidance_personal } from "./product_personalguidance_personal-training.svg";
export { default as Product_photograph } from "./product_photograph.svg";
export { default as Product_seo } from "./product_seo.svg";
export { default as Product_webbild } from "./product_webbild.svg";
export { default as Line_left } from "./Line_left.svg";

